import type {
  ParkingSlot,
  Review,
  Notification,
  CalendarEvent,
  Message,
} from "./types";

export const PARKING_SLOTS: ParkingSlot[] = [
  {
    id: "slot-1",
    name: "Avida Towers Davao",
    address: "C. M. Recto St, Poblacion District",
    city: "Davao City",
    description: "Clean and spacious parking slot located in the heart of Davao. 24/7 security and CCTV coverage. Easy access from the main road.",
    price: 50,
    rating: 5,
    reviewCount: 67,
    amenities: ["CCTV", "Security Guard", "24/7 Access"],
    vehicleTypes: ["Sedan", "SUV", "Motorcycle"],
    images: ["/images/slot-placeholder.jpg"],
    availability: [
      { day: "Mon", open: true, from: "08:00", to: "23:00" },
      { day: "Tue", open: true, from: "08:00", to: "23:00" },
      { day: "Wed", open: true, from: "08:00", to: "23:00" },
      { day: "Thu", open: true, from: "08:00", to: "23:00" },
      { day: "Fri", open: true, from: "08:00", to: "23:00" },
      { day: "Sat", open: true, from: "08:00", to: "23:00" },
      { day: "Sun", open: false, from: "08:00", to: "23:00" },
    ],
    hostId: "host-1",
    hostName: "Andrew Jacob Lomanta",
    hostSince: 2020,
    hostBookings: 87,
    isRecommended: true,
    totalBookings: 67,
    totalEarned: 67500,
  },
  {
    id: "slot-2",
    name: "SM Lanang Premier",
    address: "JP Laurel Ave, Lanang",
    city: "Davao City",
    description: "Covered parking near SM Lanang. EV charging stations available. Perfect for shoppers and office workers.",
    price: 40,
    rating: 4,
    reviewCount: 42,
    amenities: ["CCTV", "EV Charging", "Sheltered"],
    vehicleTypes: ["Sedan", "SUV", "Van", "PUV"],
    images: ["/images/slot-placeholder.jpg"],
    availability: [
      { day: "Mon", open: true, from: "08:00", to: "21:00" },
      { day: "Tue", open: true, from: "08:00", to: "21:00" },
      { day: "Wed", open: true, from: "08:00", to: "21:00" },
      { day: "Thu", open: true, from: "08:00", to: "21:00" },
      { day: "Fri", open: true, from: "08:00", to: "22:00" },
      { day: "Sat", open: true, from: "09:00", to: "22:00" },
      { day: "Sun", open: true, from: "10:00", to: "20:00" },
    ],
    hostId: "host-2",
    hostName: "Maria Santos",
    hostSince: 2021,
    hostBookings: 54,
    isRecommended: true,
    totalBookings: 42,
    totalEarned: 33600,
  },
  {
    id: "slot-3",
    name: "Abreeza Mall Parking",
    address: "J.P. Laurel Avenue, Bajada",
    city: "Davao City",
    description: "Private slot near Abreeza Mall. Sheltered and secure. Great for daily parking needs.",
    price: 35,
    rating: 4,
    reviewCount: 28,
    amenities: ["CCTV", "Sheltered"],
    vehicleTypes: ["Sedan", "Motorcycle"],
    images: ["/images/slot-placeholder.jpg"],
    availability: [
      { day: "Mon", open: true, from: "07:00", to: "22:00" },
      { day: "Tue", open: true, from: "07:00", to: "22:00" },
      { day: "Wed", open: true, from: "07:00", to: "22:00" },
      { day: "Thu", open: true, from: "07:00", to: "22:00" },
      { day: "Fri", open: true, from: "07:00", to: "22:00" },
      { day: "Sat", open: true, from: "08:00", to: "20:00" },
      { day: "Sun", open: false, from: "08:00", to: "20:00" },
    ],
    hostId: "host-3",
    hostName: "Jose Reyes",
    hostSince: 2022,
    hostBookings: 31,
    isRecommended: false,
    totalBookings: 28,
    totalEarned: 19600,
  },
  {
    id: "slot-4",
    name: "Damosa Land IT Park",
    address: "J.P. Laurel Ave, Damosa, Lanang",
    city: "Davao City",
    description: "IT Park area parking slot. EV charging available. Perfect for tech workers and daily commuters.",
    price: 45,
    rating: 5,
    reviewCount: 19,
    amenities: ["CCTV", "EV Charging", "Security Guard"],
    vehicleTypes: ["Sedan", "SUV", "Motorcycle", "Van"],
    images: ["/images/slot-placeholder.jpg"],
    availability: [
      { day: "Mon", open: true, from: "06:00", to: "23:00" },
      { day: "Tue", open: true, from: "06:00", to: "23:00" },
      { day: "Wed", open: true, from: "06:00", to: "23:00" },
      { day: "Thu", open: true, from: "06:00", to: "23:00" },
      { day: "Fri", open: true, from: "06:00", to: "23:00" },
      { day: "Sat", open: true, from: "08:00", to: "20:00" },
      { day: "Sun", open: false, from: "08:00", to: "18:00" },
    ],
    hostId: "host-4",
    hostName: "Liza Cruz",
    hostSince: 2023,
    hostBookings: 22,
    isRecommended: true,
    totalBookings: 19,
    totalEarned: 17100,
  },
  {
    id: "slot-5",
    name: "Magsaysay Park Area",
    address: "R. Magsaysay Avenue, Agdao",
    city: "Davao City",
    description: "Open lot parking near Magsaysay Park. Budget-friendly option for downtown Davao visitors.",
    price: 25,
    rating: 3,
    reviewCount: 15,
    amenities: ["CCTV"],
    vehicleTypes: ["Sedan", "Motorcycle", "Pickup Truck"],
    images: ["/images/slot-placeholder.jpg"],
    availability: [
      { day: "Mon", open: true, from: "06:00", to: "20:00" },
      { day: "Tue", open: true, from: "06:00", to: "20:00" },
      { day: "Wed", open: true, from: "06:00", to: "20:00" },
      { day: "Thu", open: true, from: "06:00", to: "20:00" },
      { day: "Fri", open: true, from: "06:00", to: "20:00" },
      { day: "Sat", open: true, from: "07:00", to: "18:00" },
      { day: "Sun", open: false, from: "07:00", to: "18:00" },
    ],
    hostId: "host-5",
    hostName: "Rodrigo Dela Cruz",
    hostSince: 2022,
    hostBookings: 18,
    isRecommended: false,
    totalBookings: 15,
    totalEarned: 7500,
  },
  {
    id: "slot-6",
    name: "Gaisano Mall Parking",
    address: "Ilustre Street, Poblacion",
    city: "Davao City",
    description: "Private slot behind Gaisano Mall. 24/7 access with security guard. Walking distance to city hall.",
    price: 30,
    rating: 4,
    reviewCount: 33,
    amenities: ["CCTV", "Security Guard", "24/7 Access", "Sheltered"],
    vehicleTypes: ["Sedan", "SUV", "Van", "PUV"],
    images: ["/images/slot-placeholder.jpg"],
    availability: [
      { day: "Mon", open: true, from: "00:00", to: "23:59" },
      { day: "Tue", open: true, from: "00:00", to: "23:59" },
      { day: "Wed", open: true, from: "00:00", to: "23:59" },
      { day: "Thu", open: true, from: "00:00", to: "23:59" },
      { day: "Fri", open: true, from: "00:00", to: "23:59" },
      { day: "Sat", open: true, from: "00:00", to: "23:59" },
      { day: "Sun", open: true, from: "00:00", to: "23:59" },
    ],
    hostId: "host-1",
    hostName: "Andrew Jacob Lomanta",
    hostSince: 2020,
    hostBookings: 87,
    isRecommended: true,
    totalBookings: 33,
    totalEarned: 19800,
  },
];

export const HOST_SLOTS: ParkingSlot[] = PARKING_SLOTS.filter(
  (s) => s.hostId === "host-1"
);

export const REVIEWS: Review[] = [
  {
    id: "rev-1",
    slotId: "slot-1",
    userId: "user-1",
    userName: "Shanaiah Cava",
    rating: 5,
    comment: "Very clean and spacious parking slot. Super convenient location. Will definitely book again!",
    date: "November 13, 2026",
  },
  {
    id: "rev-2",
    slotId: "slot-1",
    userId: "user-2",
    userName: "Shanaiah Cava",
    rating: 5,
    comment: "Great parking spot! The security is very reliable and the host is easy to contact. 10/10!",
    date: "November 13, 2026",
  },
  {
    id: "rev-3",
    slotId: "slot-1",
    userId: "user-3",
    userName: "Miguel Torres",
    rating: 5,
    comment: "Very convenient location and the host is very responsive. Highly recommended!",
    date: "November 10, 2026",
  },
  {
    id: "rev-4",
    slotId: "slot-2",
    userId: "user-1",
    userName: "Shanaiah Cava",
    rating: 4,
    comment: "Good spot. EV charging is a big plus. A bit pricey but worth it.",
    date: "October 22, 2026",
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    type: "booking",
    title: "New booking confirmed",
    message: "Your slot at Avida Towers Davao has been booked for May 15.",
    read: false,
    date: "2 min ago",
    link: "/host/calendar",
  },
  {
    id: "notif-2",
    type: "review",
    title: "New review received",
    message: "Shanaiah Cava left a 5-star review on your parking slot.",
    read: false,
    date: "1 hour ago",
    link: "/host/slots",
  },
  {
    id: "notif-3",
    type: "message",
    title: "New message from driver",
    message: "Miguel Torres: Is the slot available for overnight parking?",
    read: true,
    date: "Yesterday",
    link: "/host/messages",
  },
  {
    id: "notif-4",
    type: "system",
    title: "Booking reminder",
    message: "You have a booking starting tomorrow at 6:00 AM.",
    read: true,
    date: "Yesterday",
  },
];

export const CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: "evt-1",
    slotId: "slot-1",
    slotName: "Avida Towers Davao",
    driverName: "Shanaiah Cava",
    date: "2026-05-15",
    startTime: "06:00",
    endTime: "09:00",
    status: "confirmed",
  },
  {
    id: "evt-2",
    slotId: "slot-1",
    slotName: "Avida Towers Davao",
    driverName: "Miguel Torres",
    date: "2026-05-15",
    startTime: "10:00",
    endTime: "14:00",
    status: "confirmed",
  },
  {
    id: "evt-3",
    slotId: "slot-6",
    slotName: "Gaisano Mall Parking",
    driverName: "Juan dela Cruz",
    date: "2026-05-16",
    startTime: "08:00",
    endTime: "12:00",
    status: "pending",
  },
];

export const MESSAGES: Message[] = [
  {
    id: "msg-1",
    fromId: "user-1",
    fromName: "Shanaiah Cava",
    preview: "Hi! Is the slot still available for tomorrow?",
    date: "2 min ago",
    read: false,
    slotName: "Avida Towers Davao",
  },
  {
    id: "msg-2",
    fromId: "user-2",
    fromName: "Miguel Torres",
    preview: "Is overnight parking allowed? I'll be there by midnight.",
    date: "1 hour ago",
    read: false,
    slotName: "Avida Towers Davao",
  },
  {
    id: "msg-3",
    fromId: "user-3",
    fromName: "Juan dela Cruz",
    preview: "Thank you for confirming my booking. See you tomorrow!",
    date: "Yesterday",
    read: true,
    slotName: "Gaisano Mall Parking",
  },
  {
    id: "msg-4",
    fromId: "user-4",
    fromName: "Maria Santos",
    preview: "Can I extend my booking by 2 more hours?",
    date: "2 days ago",
    read: true,
    slotName: "Avida Towers Davao",
  },
];
